services:
  - type: web
    name: lol-stats-app
    env: node
    buildCommand: npm run install-all && npm run build
    startCommand: npm start
    envVars:
      - key: RIOT_API_KEY
        sync: false
      - key: NODE_ENV
        value: production
